swagger: '2.0'
schemes:
  - https
host: endpoint.ainize.ai
basePath: /minhoryang/hangul-ipsum
paths:
  /api/generator:
    post:
      responses:
        '200':
          description: Success
      consumes:
        - application/x-www-form-urlencoded
      summary: 지금 당장 무의미한 한글 문장을 생성합니다.
      operationId: get_ipsum
      tags:
        - Hangul-Ipsum
      parameters:
        - name: paragraphs
          in: formData
          type: integer
          format: int64
          required: true
          description: 몇 문장이나 생성하시겠습니까? 
          default: 1
        - name: length
          in: formData
          type: string
          enum: [ "long", "medium", "short"]
          description: 생성할 문장 길이입니다.
          required: true
          default: short
        - name: text_source_ids[]
          in: formData
          type: integer
          format: int64
          required: true
          description: "샘플로 사용할 데이터를 고릅니다."
          enum: [1,2]
          default: 1
info:
  title: Hangul-Ipsum
  version: 0.1.0
  description: |
    # 한글입숨
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: Hangul-Ipsum
    description: 무의미한 한글 텍스트 생성기입니다
responses:
  ParseError:
    description: When a mask can't be parsed
  MaskError:
    description: When any error occurs on mask
